### ISSUE TITLE
Missing or stray quote

### ISSUE THREAD

**Issue by rzhenis** [javierjulio/salesforce_bulk#12]
Hi there,
When I am trying to get result for batches that have records with apostrophes in their fields, I receive the following error. 
Missing or stray quote in line 1 (CSV::MalformedCSVError)
        from /home/rauza/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/csv.rb:1817:in `each'
        from /home/rauza/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/csv.rb:1817:in`block in shift'
        from /home/rauza/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/csv.rb:1777:in `loop'
        from /home/rauza/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/csv.rb:1777:in`shift'
        from /home/rauza/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/csv.rb:1719:in `each'
        from /home/rauza/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/csv.rb:1298:in`parse'
Can you add a code in client.batch_result to escape special characters please?

**Comment by javierjulio** [comment]
@rzhenis master has just been updated to only work with Ruby 2.x and support for Rails 4.x with travis coverage for all major versions of both. Its been awhile since you reported but if you can try the master branch and let me know if you're still having trouble on Ruby 2.x and/or anything else funky I'd appreciate it.
